### ISSUE TITLE
[question] can a new release be done?

### ISSUE THREAD

**Issue by Gounlaf** [mcustiel/phiremock-common#2]
Hi,

Can you release current version -  if it's stable - ?
Version 1.2.1 requires `symfony/cache:>=3.1 <5.0`; it has been removed in master
So right know i'm stuck on symfony/cache:4.x and it's a bit annoying =/

Thanks,

Regards.

Edit: And i can't use phiremock-client:dev-master ; it's unfortunately instable

**Comment by mcustiel** [comment]
Thanks for the PR @Gounlaf, but please don't use this as it's completely unstable. Also client and server are unstable. The versions mean nothing as this is still WIP.

**Comment by Gounlaf** [comment]
> Thanks for the PR @Gounlaf, but please don't use this as it's completely unstable. Also client and server are unstable. The versions mean nothing as this is still WIP.

So what should I use? `mcustiel/phiremock` only?

**Comment by mcustiel** [comment]
Yes, right now that's the stable.
I don't have a lot of free time since my son was born so I work on this only when I have enough time to add some value to it. But I promise to release a stable version of common/client/server configuration on the first half of this year.
Thank you anyhow for using phiremock and for collaborating in the project.

**Comment by Gounlaf** [comment]
> I don't have a lot of free time since my son was born so I work on this only when I have enough time to add some value to it

Family first :)

So I will use "the big bundle"
